apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    heritage: helm
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    release: v1.0
